import 'package:flutter/foundation.dart';

/// Maps logged-in user identifiers to a signature PNG under [assets/signatures/].
///
/// **Keys** can be numeric `employee_id` / `employeeId`, or `employee_code` text —
/// whatever your login API returns (see [candidateKeysForSignatureLookup]).
///
/// Edit [employeeIdToSignatureAsset] when staff or files change.
class ReceiptSignatureConfig {
  ReceiptSignatureConfig._();

  static const String signature1 = 'assets/signatures/signature1.png';
  static const String signature2 = 'assets/signatures/signature2.png';
  static const String srimalSir = 'assets/signatures/Srimal_test.png';
  static const String gayanSignature = 'assets/signatures/Gayan.png';
  static const String tharinduSignature = 'assets/signatures/Tharindu.png';


  /// Map **one or more** identifiers per person (e.g. `'26'` and `'EMP026'`).
  static const Map<String, String> employeeIdToSignatureAsset = {
    '19': srimalSir,
    '80': gayanSignature,
    '52': tharinduSignature,
  };

  static String? _trimmed(dynamic v) {
    if (v == null) return null;
    if (v is int) return v.toString();
    if (v is double) {
      if (v.isFinite && v % 1 == 0) return v.toInt().toString();
      return v.toString().trim();
    }
    final s = v.toString().trim();
    if (s.isEmpty) return null;
    // String "26.0" from JSON / serialization must still match map key "26".
    final asInt = int.tryParse(s);
    if (asInt != null) return asInt.toString();
    final asDouble = double.tryParse(s);
    if (asDouble != null &&
        asDouble.isFinite &&
        asDouble % 1 == 0) {
      return asDouble.toInt().toString();
    }
    return s;
  }

  static int? _parseIntKey(String key) {
    final i = int.tryParse(key);
    if (i != null) return i;
    final d = double.tryParse(key);
    if (d != null && d.isFinite && d % 1 == 0) return d.toInt();
    return null;
  }

  /// Values we try, in order, against [employeeIdToSignatureAsset] keys.
  static List<String> candidateKeysForSignatureLookup(
      Map<String, dynamic>? user) {
    if (user == null) return const [];
    final out = <String>[];
    void add(String? s) {
      if (s == null) return;
      if (!out.contains(s)) out.add(s);
    }

    // Prefer real employee ids first (same order as [home_screen] airport gate).
    add(_trimmed(user['employeeId']));
    add(_trimmed(user['employee_id']));
    add(_trimmed(user['employeeID']));
    add(_trimmed(user['EmployeeId']));
    add(_trimmed(user['EMPLOYEE_ID']));
    add(_trimmed(user['id']));
    add(_trimmed(user['user_id']));
    add(_trimmed(user['userId']));
    // Some backends only send staff code — you can map those in [employeeIdToSignatureAsset].
    add(_trimmed(user['employeeCode']));
    add(_trimmed(user['employee_code']));

    return out;
  }

  /// First id-like value (for logs / diagnostics).
  static String? employeeIdOf(Map<String, dynamic>? user) {
    final c = candidateKeysForSignatureLookup(user);
    return c.isEmpty ? null : c.first;
  }

  /// PNG path for this user, or `null` if no row matches any candidate key.
  static String? signatureAssetForUser(Map<String, dynamic>? user) {
    final candidates = candidateKeysForSignatureLookup(user);
    for (final id in candidates) {
      final path = employeeIdToSignatureAsset[id];
      if (path != null) return path;
    }
    // Map keys are strings; API may send numeric types that stringify oddly.
    // Match map entries by parsed integer (e.g. key "26" vs candidate "26.0").
    final wantInts = <int>{};
    for (final c in candidates) {
      final n = _parseIntKey(c);
      if (n != null) wantInts.add(n);
    }
    for (final e in employeeIdToSignatureAsset.entries) {
      final k = _parseIntKey(e.key);
      if (k != null && wantInts.contains(k)) return e.value;
    }
    if (candidates.isNotEmpty) {
      debugPrint(
        '[ReceiptSignature] No PNG mapped for tried keys: $candidates. '
        'Add one of these strings to employeeIdToSignatureAsset in '
        'receipt_signature_config.dart',
      );
    } else {
      debugPrint(
        '[ReceiptSignature] User map has no employeeId / employee_id / id / '
        'employeeCode fields — cannot resolve signature.',
      );
    }
    return null;
  }

  /// Shown in PDF “Generated by” / signature line.
  static String displayName(Map<String, dynamic>? user) {
    if (user == null) return '—';
    final name = (user['preferred_name'] ??
            user['preferredName'] ??
            user['name'] ??
            user['full_name'] ??
            user['username'] ??
            '')
        .toString()
        .trim();
    return name.isEmpty ? 'Staff' : name;
  }
}
